### ISSUE TITLE
Sidebar Enhancements

### ISSUE THREAD

**Issue by Connorelsea** [nilium/st-theme-freesia#7]
Hey. I've been using this theme and color scheme for about a year now and have really loved it. The only problem I have had is visibility of the sidebar. Sometimes it is hard to see items at a glance especially with long/deep folder structures.

Do you think it would be possible to maybe soften the color of children files (not folders), such as "Dashboard.js" and "Dashboard.test.js". I feel like this could increase readability. There may also be other ways to increase readability though.

![image](https://cloud.githubusercontent.com/assets/1844458/19456103/90b99258-9485-11e6-9a1b-23eb6b04fe60.png)

**Comment by nilium** [comment]
I'll have to think about it. You can try modifying the sidebar tree colors in the theme files and see if you can come up with something that works for you in the meantime.

(Typing from phone, may be terse.)
